### ISSUE TITLE
Trate constantes como constantes

### ISSUE THREAD

**Issue by kyriosdata** [jc00973/cs-2019-01#10]
O seguinte trecho de código foi extraído da versão Java: 

```
int i = n / 100;
int j = n % 100;
```
uma versão melhor é 
```
final int i = n / 100;
final int j = n % 100;
```

Você precisa fazer a correção e aplicar a ideia no restante do código.

**Comment by jc00973** [comment]
Correção já realizada nos códigos em Java e JS.
