### ISSUE TITLE
Funções em arquivos próprios

### ISSUE THREAD

**Issue by kyriosdata** [jc00973/cs-2019-01#5]
Pode-se organizar cada função em seu próprio arquivo (JS), conforme sua opção no momento. Contudo, deve ser um arquivo JS. O arquivo Exercicio09.js, por exemplo, não é JS. Remova as linhas <script> e </script>. Isso vale para todos os arquivos com esta mesma estrutura.

**Comment by jc00973** [comment]
Correções efetuadas. Todos as funções em JS foram colocadas em um mesmo arquivo.
