### ISSUE TITLE
Leiaute (JS)

### ISSUE THREAD

**Issue by kyriosdata** [jc00973/cs-2019-01#6]
O código não segue uma padronização de codificação. O leiuate "padrão" não é estabelecido. Isto pode ser simplesmente resolvido com um editor com capacidade de formatação do código. Observe, por exemplo, a linha abaixo extraída de Exercicio14
```
if(n%i == 0) return false;
```

O indicado equivalente, atendendo leiaute é

```
if (n % i == 0) {
    return false;
}
```

**Comment by jc00973** [comment]
Código formatado.
